/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as paymentsSolDec082022Sol from "./PaymentsSolDec082022.sol";
export type { paymentsSolDec082022Sol };
